// AUTO-GENERATED by GitHub Actions, DO NOT EDIT.
// 包含 OPT_algo 全部算法。
#pragma once

namespace opt_algo {

// ==== math/quick_pow/iterative/quick_pow.hpp ====
template <typename T>
    T quick_pow_iterative(T a, T b, T mod)
    {
        T res = 1 % mod;
        a %= mod;
        while (b)
        {
            if (b & 1)
            {
                res = (res * a) % mod;
            }
            a = (a * a) % mod;
            b >>= 1;
        }
        return res;
    }

// ==== math/quick_pow/recursive/quick_pow.hpp ====
template <typename T>
    T quick_pow_recursive(T a, T b, T mod)
    {
        if (b == 0)
        {
            return 1 % mod;
        }
        T half = quick_pow_recursive(a, b / 2, mod);
        half = (half * half) % mod;
        if (b % 2)
        {
            half = (half * a) % mod;
        }
        return half;
    }

} // namespace opt_algo
